import {
  ArrowsOutIcon,
  BookOpenIcon,
  BrainIcon,
  CaretRightIcon,
  CaretLeftIcon,
  CheckCircleIcon,
  ChatsCircleIcon,
  ClockIcon,
  ClockCounterClockwiseIcon,
  DotsThreeIcon,
  FloppyDiskIcon,
  FlowArrowIcon,
  GitBranchIcon,
  GraphIcon,
  ChartBarIcon,
  HandIcon,
  KeyboardIcon,
  LightningIcon,
  ListChecksIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  PaperclipIcon,
  PaperPlaneRightIcon,
  PlayIcon,
  PlusIcon,
  SignOutIcon,
  SpinnerGapIcon,
  StopCircleIcon,
  SunIcon,
  MoonIcon,
  SlidersHorizontalIcon,
  TrashIcon,
  UserGearIcon,
  WrenchIcon,
  XIcon,
} from '@phosphor-icons/react'

const icons = {
  flow: GraphIcon,
  play: PlayIcon,
  save: FloppyDiskIcon,
  plus: PlusIcon,
  trigger: LightningIcon,
  condition: GitBranchIcon,
  action: FlowArrowIcon,
  delay: ClockIcon,
  finish: StopCircleIcon,
  llm: BrainIcon,
  knowledge: BookOpenIcon,
  output: SignOutIcon,
  agent: UserGearIcon,
  classifier: ListChecksIcon,
  human: HandIcon,
  zoomIn: MagnifyingGlassPlusIcon,
  zoomOut: MagnifyingGlassMinusIcon,
  fit: ArrowsOutIcon,
  trash: TrashIcon,
  chevron: CaretRightIcon,
  search: MagnifyingGlassIcon,
  close: XIcon,
  edge: FlowArrowIcon,
  chats: ChatsCircleIcon,
  send: PaperPlaneRightIcon,
  attach: PaperclipIcon,
  settings: SlidersHorizontalIcon,
  tool: WrenchIcon,
  success: CheckCircleIcon,
  history: ClockCounterClockwiseIcon,
  more: DotsThreeIcon,
  loading: SpinnerGapIcon,
  usage: ChartBarIcon,
  activity: KeyboardIcon,
  previous: CaretLeftIcon,
  next: CaretRightIcon,
  sun: SunIcon,
  moon: MoonIcon,
}

function Icon({ name, size = 18, weight = 'regular' }) {
  const Component = icons[name] ?? FlowArrowIcon
  return <Component className="icon" size={size} weight={weight} aria-hidden="true" />
}

export default Icon
